default_install_hook_types: [ pre-commit, commit-msg ]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system  # use system python
        types: [ python ]
        args: [ --strict ]

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [ commit-msg ]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0  # Use latest version
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ --strict,
                feat,
                fix,
                refactor,
                perf,
                style,
                test,
                docs,
                build,
                ops,
                chore
        ] # commit types like [feat, fix, ci, chore]
